skillByAbility = {
	["Mining"] = 1,
	["Woodcutting"] = 2,
	["Construction"] = 3,
	["Smithing"] = 4,
	["Fishing"] = 6,
	["Total Level"] = 7,
}
genderName = {
	[0] = {name = "female", subName = "Woman", color = "#e79dff"},
	[1] = {name = "male", subName = "Man", color = "#9dd7ff"},
}

clanNameById = {
  [1] = "volcanic",
  [2] = "seavell",
  [3] = "naturia",
  [4] = "gardestrike",
  [5] = "psycraft",
  [6] = "malefic",
  [7] = "raibolt",
  [8] = "wingeon",
  [9] = "orebound",
}

clanColor = {
  [1] = "#ff7268",
  [2] = "#68c8ff",
  [3] = "#68ff93",
  [4] = "#ff8d5f",
  [5] = "#f0b7f8",
  [6] = "#a58fd9",
  [7] = "#fae488",
  [8] = "#cbcbcb",
  [9] = "#b7b5e3",
}

lookClans = {
  [1] = {"Volcanic Spark", "Volcanic Flame", "Volcanic Firetamer", "Volcanic Pyromancer", "Volcanic Master"},
  [2] = {"Seavell Drop", "Seavell Icelake","Seavell Waterfall","Seavell Frost","Seavell King"},
  [3] = {"Naturia Seed", "Naturia Sprout","Naturia Webhead","Naturia Woodtrunk","Naturia Keeper"},
  [4] = {"Gardestrike Fist", "Gardestrike Tamer","Gardestrike Fighter","Gardestrike Deathhand","Gardestrike Champion"},
  [5] = {"Psycraft Mind", "Psycraft Brain","Psycraft Scholar","Psycraft Telepath","Psycraft Medium"},
  [6] = {"Malefic Troublemaker", "Malefic Venomancer","Malefic Spectre","Malefic Nightwalker","Malefic Lord"},
  [7] = {"Raibolt Shock", "Raibolt Watt","Raibolt Electrician","Raibolt Overcharged","Raibolt Legend"},
  [8] = {"Wingeon Cloud", "Wingeon Wind","Wingeon Sky","Wingeon Falcon","Wingeon Dragon"},
  [9] = {"Orebound Sand", "Orebound Rock","Orebound Solid","Orebound Hardskin","Orebound Hero"},
}

lookClansShe = {
  [1] = {"Volcanic Spark", "Volcanic Flame", "Volcanic Firetamer", "Volcanic Pyromancer", "Volcanic Master"},
  [2] = {"Seavell Drop", "Seavell Icelake","Seavell Waterfall","Seavell Frost","Seavell Queen"},
  [3] = {"Naturia Seed", "Naturia Sprout","Naturia Webhead","Naturia Woodtrunk","Naturia Keeper"},
  [4] = {"Gardestrike Fist", "Gardestrike Tamer","Gardestrike Fighter","Gardestrike Deathhand","Gardestrike Champion"},
  [5] = {"Psycraft Mind", "Psycraft Brain","Psycraft Scholar","Psycraft Telepath","Psycraft Medium"},
  [6] = {"Malefic Troublemaker", "Malefic Venomancer","Malefic Spectre","Malefic Nightwalker","Malefic Lady"},
  [7] = {"Raibolt Shock", "Raibolt Watt","Raibolt Electrician","Raibolt Overcharged","Raibolt Legend"},
  [8] = {"Wingeon Cloud", "Wingeon Wind","Wingeon Sky","Wingeon Falcon","Wingeon Dragon"},
  [9] = {"Orebound Sand", "Orebound Rock","Orebound Solid","Orebound Hardskin","Orebound Heroine"},
}

townsName = {
  [1] = "Saffron City",
  [2] = "Cerulean City",
  [3] = "Lavender",
  [4] = "Fuchsia City",
  [5] = "Celadon City",
  [6] = "Viridian City",
  [7] = "Vermilion City",
  [8] = "Pewter City",
  [9] = "Pallet Town",
  [10] = "Cinnabar City",
  [11] = "Snow City",
  [12] = "Trade Center",
  [13] = "Test Pvp",
  [14] = "Golden Arena",
  [15] = "Lightstorm Island",
  [16] = "Diving Spot",
  [17] = "Lava Town",
  [18] = "New Bark Town",
  [19] = "Cherrygrove City",
  [20] = "Violet City",
  [21] = "Union Cave",
  [22] = "Azalea Town",
  [23] = "Goldenrod City",
  [24] = "National Park",
  [25] = "Ecruteak City",
  [26] = "Olivine City",
  [27] = "Cianwood City",
  [28] = "Mahogany Town",
  [29] = "Blackthorn City",
  [30] = "Tournament",
  [31] = "Coliseum",
  [32] = "Area Inicial",
}

skillsItem = {
  ["Seed"] = 11230,
  ["Shrimps"] = 3581,
  ["Fish"] = 3579,
  ["Big Shrimp"] = 3597,
  ["Big Fish"] = 3578,
  ["Worms"] = 3492,
  ["Fishing Baits"] = 3595,
  ["Slow Tail"] = 11264,
  ["Electric Rat Tail"] = 13573,
  ["Steak"] = 3582,
  ["Big Steak"] = 3580,
  ["Special Lure"] = 3577,
  ["Linearly Guided Hypnose"] = 11273,
  ["Feather"] = 11267,
  ["Old Rod"] = 16160,
  ["Small Fishing Net"] = 16165,
  ["Large Fishing Net"] = 46382,
  ["Good Rod"] = 16161,
  ["Copper"] = 16088,
  ["Tin"] = 16087,
  ["Iron"] = 16084,
  ["Silver"] = 16089,
  ["Coal"] = 16085,
  ["Gold"] = 16086,

  ["Copper Ore"] = 16088,
  ["Tin Ore"] = 16087,
  ["Iron Ore"] = 16084,
  ["Silver Ore"] = 16089,
  ["Coal Ore"] = 16085,
  ["Gold Ore"] = 16086,

  ["Normal Log"] = 16874,
  ["Oak Log"] = 16875,
  ["Willow Log"] = 16876,
  ["Maple Log"] = 16877,
  ["Teak Log"] = 16878,

  ["Old Axe"] = 16870,
  ["Good Axe"] = 16871,
  ["Super Axe"] = 16872,
  
  ["Old Pickaxe"] = 356,
  ["Good Pickaxe"] = 357,
  ["Super Pickaxe"] = 358,
  
  ["Normal Plank"] = 16884,
  ["Oak Plank"] = 16885,
  ["Willow Plank"] = 16886,
  ["Maple Plank"] = 16887,
  ["Teak Plank"] = 16888,
  
  ["Bronze Nail"] = 951,
  ["Iron Nail"] = 955,
  ["Steel Nail"] = 956,
  
  ["Bronze Bar"] = 16079,
  ["Iron Bar"] = 16081,
  ["Silver Bar"] = 16080,
  ["Steel Bar"] = 16938,
  ["Gold Bar"] = 16082,
  ["Adamantium Bar"] = 16083,
  
  ["Old Hammer"] = 3459,
  ["Good Hammer"] = 3460,
  ["Saw"] = 3461,
  ["Work Knife"] = 3298,
  ["Cotton"] = 16991,
  ["Leaves"] = 11222,
  ["Sheep Wool"] = 13576,
  ["Wool Ball"] = 11254,
  
  ["Metal Thread"] = 16942,
  ["Wooden Chair"] = 10891,
  ["Dresser"] = 2441,
  ["Wooden Table"] = 10570,
  ["Wardrobe"] = 2449,
  ["Pendulum Clock"] = 2445,
  ["Wooden Balcony"] = 10565,
  ["Oak Chair"] = 16898,
  ["Oak Dresser"] = 16979,
  ["Oak Table"] = 16908,
  ["Rustic Oak Chair"] = 16961,
  ["Box"] = 2469,
  ["Oak Wardrobe"] = 16911,
  ["Strong Oak Table"] = 16975,
  ["Oak Pendulum Clock"] = 16923,
  ["Oak Balcony"] = 16935,
  ["Jungle Balcony"] = 16972,
  ["Willow Chair"] = 16902,
  ["Willow Dresser"] = 16983,
  ["Willow Table"] = 16909,
  ["Rustic Willow Chair"] = 16965,
  ["Willow Wardrobe"] = 16915,
  ["Strong Willow Table"] = 16976,
  ["Willow Cushion Chair"] = 16949,
  ["Willow Pendulum Clock"] = 16927,
  ["Willow Balcony"] = 16936,
  ["Willow Jungle Balcony"] = 16973,
  ["Maple Chair"] = 16906,
  ["Maple Dresser"] = 16987,
  ["Maple Table"] = 16910,
  ["Rustic Maple Chair"] = 16969,
  ["Maple Wardrobe"] = 16919,
  ["Strong Maple Table"] = 16977,
  ["Maple Cushion Chair"] = 16953,
  ["Maple Pendulum Clock"] = 16931,
  ["Maple Balcony"] = 16937,
  ["Maple Jungle Balcony"] = 16974,
  
  ["Starter Rod"] = 21614,
  ["Novice Rod"] = 21615,
  ["Rookie Rod"] = 21616,
  ["Beginner’s Rod"] = 21617,
  ["Newbie Rod"] = 21618,
  ["Learner’s Rod"] = 21619,
  ["Super Rod"] = 21620,
  ["Elite Rod"] = 21621,
  ["Champion Rod"] = 21622,
  ["Epic Rod"] = 21623,
  ["Mythic Rod"] = 21624,
  ["Legendary Rod"] = 21625,
  ["Omega Rod"] = 21626,
  ["Z-Rod"] = 21627,
  ["Mega Rod"] = 21628,
  ["Primal Rod"] = 21629,
  ["Ultra Rod"] = 21630,
  ["Dynamax Rod"] = 21631,
  ["Eternamax Rod"] = 21632,

  ["Pokeball Bait"] = 46394,
  ["Greatball Bait"] = 46395,
  ["Ultraball Bait"] = 46396,
  ["Premierball Bait"] = 46397,
  ["Golden Ball Bait"] = 46398,
  ["Pokeball Shaped Bait"] = 46399,
  ["Greatball Shaped Bait"] = 46400,
  ["Ultraball Shaped Bait"] = 46401,
  ["Premierball Shaped Bait"] = 46402,
  ["Golden Ball Shaped Bait"] = 46403,
  ["Horned Blue and White Bait"] = 46404,
  ["Horned Red and White Bait"] = 46405,
  ["Horned Green, Red, and White Bait"] = 46406,
  ["Horned Blue, White, and Pink Bait"] = 46407,
  ["Horned Golden Bait"] = 46408,
  ["Blue Pokéball Bait"] = 46423,
  ["Black Pokéball Bait"] = 46425,
  ["Red Pokéball Bait"] = 3577,
  ["James Special Lure"] = 46429,
  ["Jessie Special Lure"] = 46430,
  ["Meowth Special Lure"] = 46431,
  ["Misty's Special Lure"] = 3588,
  ["Ho-Oh Bait"] = 46409,
  ["Rayquaza Bait"] = 46410,
  ["Kyogre Bait"] = 46411,
  ["Groudon Bait"] = 46412,
  ["Mew Bait"] = 46413,

  ["Small Branch"] = 46444,
  ["Jumbo Shrimp"] = 46428,
  ["Green Wiggler"] = 46424,
  ["Pinky Fish"] = 46426,
  ["Sunny Fish"] = 46422,
  ["Common Catch"] = 3579,
  ["Big Common Catch"] = 3578,
  ["Electric Blue Fish"] = 46416,
  ["Golden Thread"] = 46417,
  ["Copper Wire"] = 46418,
  ["Blue Snail"] = 46419,
  ["Green Snail Shell"] = 46420,
  ["Desert Scorpion"] = 46421,
  ["Volcanic Rocks"] = 46433,
  ["Light Blue Shell"] = 46435,
  ["Orange Shell"] = 46436,
  ["Locked Brown Shell"] = 46437,
  ["Locked Red and Pink Shell"] = 46438,
  ["Light Red Shell"] = 46439,
  ["Caramel Shell"] = 46440,
  ["Deep Red Shell"] = 46441,
  ["Monster Tail"] = 46448,
  ["Bamboo Piece"] = 46445,
  ["Magikarp Fin"] = 11401,
  ["Black Gravel"] = 46447,
  ["Green Orb"] = 46472,
  ["Brown Wiggler"] = 3492,
  ["Shiny Green Star"] = 46469,
  ["Light Blue Gravel"] = 46468,
  ["Light Pink Stone"] = 46467,
  ["Light Blue Stone"] = 46466,
  ["Copper Plate"] = 46464,
  ["Seaweed Piece"] = 46463,
  ["Barrel Fragment"] = 46462,
  ["Yellow Flower"] = 46461,
  ["Big Blue Flower"] = 46460,
  ["Large Monster Claw"] = 46459,
  ["Large Dried Leaf"] = 46458,
  ["Small Monster Claw"] = 46457,
  ["Yellow Star"] = 46456,
  ["Rare Blue Stone"] = 46455,
  ["Oceanic Blue Stone"] = 46454,
  ["Green Gravel"] = 46453,
  ["Spool of Thread"] = 46452,
  ["Green Sea Slime"] = 46451,
  ["Cluster of Rare Green Stones"] = 46450,
  ["Banana Peel"] = 46446,
  ["Dark Blue Thread"] = 46470,
  ["Small Shrimp"] = 3581,
  ["Large Saltwater Shrimp"] = 3597,
  ["Blue Jellyfish"] = 46414,
  ["Small Brown Snail"] = 46415,
  ["Seaweed"] = 3583,
  ["Large Brown Fish"] = 7158,
  ["Large Fat Green Fish"] = 7159,
  ["Yellow Dirt"] = 3595,
  ["Slowpoke Tail"] = 11264,
  ["Water Gem"] = 11228,
  ["seed"] = 11230,
  ["Dragon Scale"] = 13656,
  
  ["Curvaflare"] = 46543,
  ["Bonehead Goldfish"] = 46544,
  ["Azurefin"] = 46545,
  ["Dangerfin"] = 46546,
  ["Stripefin"] = 46547,
  ["Slimflare"] = 46548,
  ["Goldhead Purplefish"] = 46549,
  ["Fatshadow"] = 46550,
  ["Stonefish"] = 46551,
  ["Yellowhead Brownfish"] = 46552,
  ["Legfin"] = 46553,
  ["Flatface"] = 46554,
  ["Yelloweye Redfish"] = 46555,
  ["Greenface"] = 46556,
  ["Pinkfin Bluefish"] = 46557,
  ["Bluebright"] = 46558,
  ["Yellowfin Greenfish"] = 46559,
  ["Redstripe Grayfish"] = 46560,
  ["Pinkshadow"] = 46561,
  ["Redhead Slimfish"] = 46562,
  ["Brightfin"] = 46563,
  ["Blackhead Bluefish"] = 46564,
  ["Rosetentacle Octopus"] = 46565,
  ["Darkfin Fatfish"] = 46567,
  ["Yellowfin Brownfish"] = 46568,
  ["Trio Bluefish"] = 46569,
  ["Redeye Squid"] = 46570,
  ["Redtentacle Squid"] = 46571,
  ["Orangecrab"] = 46572,
  ["Greeneye Shrimp"] = 46573,
  ["Striped Snail"] = 46574,
  ["Pinkworm"] = 46575,
  ["Longfang Insect"] = 46576,
  
  ["snowball"] = 13651,
  ["bottle of poison"] = 11232,
  ["enchanted gem"] = 13652,
  ["band aid"] = 13653,
  ["Thread"] = 16941,
  ["water pendant"] = 11237,
  ["Squirrel Nut"] = 46443,
  ["bone"] = 11275,
  ["Monster Claw"] = 46465,
  ["Farfetch'd stick"] = 11266,
  ["squirtle hull"] = 11225,
  ["blastoise hull"] = 11339,
  ["crab claw"] = 11274,
  ["gyarados tail"] = 11215,
  ["dragon tail"] = 13644,
  ["locksmith of shell"] = 11270,
  ["seahorse tail"] = 13605,
  ["blue ball"] = 13578,
  ["giant fin"] = 13643,
  ["ice bra"] = 11235,
  ["seal tail"] = 13633,
  ["strange spike"] = 13635,
  ["horn"] = 11245,
  ["fish fin"] = 13639,
  ["future orb"] = 11261,
  ["gem star"] = 13640,
  ["piece of coral"] = 13599,
  ["psyduck mug"] = 11256,
  ["karate duck"] = 11257,
  ["nail"] = 11224,
  ["red scale"] = 13566,
  ["point of light"] = 13572,
  ["wooper horn"] = 13647,
  ["small tail"] = 13590,
  ["tentacle"] = 13600,
  ["streak tail"] = 13602,
  ["strange thing"] = 13580,
  
  ["White Shell"] = 46442,
  ["Warped Brown Stone"] = 46449,
  ["stone orb"] = 11263,
  ["ice orb"] = 11268,
  ["onix tail"] = 11272,
  ["giant ruby"] = 13645,
  ["giant emerald"] = 13703,
  ["emerald"] = 13702,
  ["small stone"] = 11404,
  ["ruby"] = 11255,
  ["earth ball"] = 13659,
  
  ["Maritime Trio"] = 46540,
  ["Oceanic Aurora"] = 46503,
  ["Deep Emerald"] = 46515,
  ["Marine Steel"] = 46535,
  ["Twilight Coral"] = 46514,
  ["Blue Tide"] = 46513,
  ["Twin Waves"] = 46541,
  ["Coral Meteorite"] = 46498,
  ["Submarine Fire"] = 46508,
  ["Tide Peak"] = 46536,
  ["Sea Treasure"] = 46502,
  ["King's Crown"] = 46434,
}

function doGetFishingItemsData()
	return skillsItem
end

skillFishInfos = {
	banner = "pescador",
	firstPanel = function() doSetupFishPanel("pokemons") end,
	buttons = {
		{icon = "magikarp", iconType = "IMAGE", name = "Pokemons", action = function() doSetupFishPanel("pokemons") end},
		{icon = 3492, iconType = "ITEM", name = "Lures", action = function() doSetupFishPanel("lures") end},
		{icon = 21614, iconType = "ITEM", name = "Rods", action = function() doSetupFishPanel("rods") end},
		{icon = 46382, iconType = "ITEM", name = "Fisheries", action = function() doSetupFishPanel("comuns") end},
	},
	panel = { -- {icon = "", iconType = "", name = "", reward = ""},
		pokemons = {
			-- Nível 1-20
			{level = 1,  pokemon = "Magikarp"},
			{level = 5,  pokemon = "Poliwag", isca = {"Pokeball Shaped Bait"}},
			{level = 10, pokemon = "Tentacool", isca = {"Horned Red and White Bait"}},
			{level = 20, pokemon = "Slowpoke", isca = {"Horned Blue and White Bait"}},
			{level = 20, pokemon = "Seel", isca = {"Horned Green, Red, and White Bait"}},
			{level = 20, pokemon = "Shellder", isca = {"Greatball Shaped Bait"}},
			{level = 15, pokemon = "Krabby", isca = {"Horned Red and White Bait"}},
			{level = 10, pokemon = "Horsea", isca = {"Ultraball Bait"}},
			{level = 10, pokemon = "Goldeen", isca = {"Greatball Bait"}},
			{level = 15, pokemon = "Wooper", isca = {"Horned Blue and White Bait"}},
			{level = 20, pokemon = "Marill", isca = {"Horned Blue and White Bait"}},
			
			-- Nível 20-40
			{level = 20, pokemon = "Squirtle", isca = {"Pokeball Bait"}},
			{level = 30, pokemon = "Wartortle", isca = {"Pokeball Bait"}},
			{level = 30, pokemon = "Poliwhirl", isca = {"Pokeball Shaped Bait"}},
			{level = 40, pokemon = "Tentacruel", isca = {"Horned Red and White Bait"}},
			{level = 35, pokemon = "Slowbro", isca = {"Horned Blue and White Bait"}},
			{level = 35, pokemon = "Dewgong", isca = {"Horned Blue, White, and Pink Bait"}},
			{level = 40, pokemon = "Cloyster", isca = {"Greatball Shaped Bait"}},
			{level = 35, pokemon = "Kingler", isca = {"Horned Red and White Bait"}},
			{level = 35, pokemon = "Seadra", isca = {"Ultraball Bait"}},
			{level = 35, pokemon = "Seaking", isca = {"Greatball Bait"}},
			{level = 20, pokemon = "Staryu", isca = {"Horned Green, Red, and White Bait"}},
			{level = 40, pokemon = "Starmie", isca = {"Horned Blue, White, and Pink Bait"}},
			{level = 40, pokemon = "Azumarill", isca = {"Horned Blue and White Bait"}},
			{level = 25, pokemon = "Chinchou", isca = {"Horned Red and White Bait"}},
			{level = 25, pokemon = "Corsola", isca = {"Horned Green, Red, and White Bait"}},
			{level = 20, pokemon = "Remoraid", isca = {"Horned Red and White Bait"}},

			-- Nível 40-60
			{level = 40, pokemon = "Psyduck", isca = {"Greatball Bait"}},
			{level = 52, pokemon = "Golduck", isca = {"Greatball Bait"}},
			{level = 50, pokemon = "Omanyte", isca = {"Horned Golden Bait"}},
			{level = 60, pokemon = "Omastar", isca = {"Horned Golden Bait"}},
			{level = 50, pokemon = "Kabuto", isca = {"Horned Golden Bait"}},
			{level = 60, pokemon = "Kabutops", isca = {"Horned Golden Bait"}},
			{level = 50, pokemon = "Dratini", isca = {"Golden Ball Bait"}},
			{level = 60, pokemon = "Dragonair", isca = {"Golden Ball Bait"}},
			{level = 40, pokemon = "Totodile", isca = {"Pokeball Shaped Bait"}},
			{level = 50, pokemon = "Croconaw", isca = {"Pokeball Shaped Bait"}},
			{level = 60, pokemon = "Feraligatr", isca = {"Ultraball Shaped Bait"}},
			{level = 60, pokemon = "Lanturn", isca = {"Horned Red and White Bait"}},
			{level = 45, pokemon = "Politoed", isca = {"Pokeball Shaped Bait"}},
			{level = 55, pokemon = "Quagsire", isca = {"Horned Blue, White, and Pink Bait"}},
			{level = 60, pokemon = "Slowking", isca = {"Horned Blue, White, and Pink Bait"}},
			{level = 48, pokemon = "Qwilfish", isca = {"Horned Red and White Bait"}},
			{level = 48, pokemon = "Octillery", isca = {"Horned Red and White Bait"}},
			{level = 55, pokemon = "Mantine", isca = {"Horned Blue, White, and Pink Bait"}},

			-- Nível 60-80
			{level = 75, pokemon = "Lapras", isca = {"Premierball Bait"}},
			{level = 68, pokemon = "Vaporeon", isca = {"Premierball Bait"}},
			{level = 60, pokemon = "Blastoise", isca = {"Pokeball Bait"}},
			{level = 60, pokemon = "Poliwrath", isca = {"Ultraball Shaped Bait"}},
			{level = 80, pokemon = "Gyarados", isca = {"Golden Ball Bait"}},
			{level = 80, pokemon = "Kingdra", isca = {"Ultraball Bait"}},

			-- Nível 80-100
			{level = 90, pokemon = "Dragonite", isca = {"Golden Ball Bait"}},
		},
		lures = {
			{level = 1, isca = "Pokeball Bait", desc = "", quality = 5},
			{level = 1, isca = "Greatball Bait", desc = "", quality = 10},
			{level = 1, isca = "Ultraball Bait", desc = "", quality = 15},
			{level = 1, isca = "Premierball Bait", desc = "", quality = 20},
			{level = 1, isca = "Golden Ball Bait", desc = "", quality = 40},
			
			{level = 1, isca = "Pokeball Shaped Bait", desc = "", quality = 5},
			{level = 1, isca = "Greatball Shaped Bait", desc = "", quality = 15},
			{level = 1, isca = "Ultraball Shaped Bait", desc = "", quality = 25},
			{level = 1, isca = "Premierball Shaped Bait", desc = "", quality = 35},
			{level = 1, isca = "Golden Ball Shaped Bait", desc = "", quality = 50},
			
			{level = 1, isca = "Horned Blue and White Bait", desc = "", quality = 10},
			{level = 1, isca = "Horned Red and White Bait", desc = "", quality = 20},
			{level = 1, isca = "Horned Green, Red, and White Bait", desc = "", quality = 30},
			{level = 1, isca = "Horned Blue, White, and Pink Bait", desc = "", quality = 40},
			{level = 1, isca = "Horned Golden Bait", desc = "", quality = 50},
			
			{level = 1, isca = "Blue Pokéball Bait", desc = "", quality = 35},
			{level = 1, isca = "Black Pokéball Bait", desc = "", quality = 35},
			{level = 1, isca = "Red Pokéball Bait", desc = "", quality = 35},
			
			{level = 1, isca = "James Special Lure", desc = "", quality = 45},
			{level = 1, isca = "Jessie Special Lure", desc = "", quality = 45},
			{level = 1, isca = "Meowth Special Lure", desc = "", quality = 45},
			{level = 1, isca = "Misty's Special Lure", desc = "", quality = 45},
			
			{level = 1, isca = "Ho-Oh Bait", desc = "", quality = 100},
			{level = 1, isca = "Rayquaza Bait", desc = "", quality = 100},
			{level = 1, isca = "Kyogre Bait", desc = "", quality = 100},
			{level = 1, isca = "Groudon Bait", desc = "", quality = 100},
			{level = 1, isca = "Mew Bait", desc = "", quality = 100},
		},
		rods = {
			{level = 1, rod = "Small Fishing Net", quality = 5},
			{level = 1, rod = "Large Fishing Net", quality = 45},
			{level = 1, rod = "Starter Rod", quality = 5},
			{level = 1, rod = "Novice Rod", quality = 10},
			{level = 1, rod = "Rookie Rod", quality = 15},
			{level = 1, rod = "Beginner’s Rod", quality = 20},
			{level = 1, rod = "Newbie Rod", quality = 25},
			{level = 1, rod = "Learner’s Rod", quality = 30},
			{level = 1, rod = "Super Rod", quality = 35},
			{level = 1, rod = "Elite Rod", quality = 40},
			{level = 1, rod = "Champion Rod", quality = 45},
			{level = 1, rod = "Epic Rod", quality = 50},
			{level = 1, rod = "Mythic Rod", quality = 55},
			{level = 1, rod = "Legendary Rod", quality = 60},
			{level = 1, rod = "Omega Rod", quality = 65},
			{level = 1, rod = "Z-Rod", quality = 70},
			{level = 1, rod = "Mega Rod", quality = 75},
			{level = 1, rod = "Primal Rod", quality = 80},
			{level = 1, rod = "Ultra Rod", quality = 85},
			{level = 1, rod = "Dynamax Rod", quality = 90},
			{level = 1, rod = "Eternamax Rod", quality = 100},
		},
		comuns = {
            {name = "Curvaflare", value = 000},
            {name = "Bonehead Goldfish", value = 000},
            {name = "Azurefin", value = 000},
            {name = "Dangerfin", value = 000},
            {name = "Stripefin", value = 000},
            {name = "Slimflare", value = 000},
            {name = "Goldhead Purplefish", value = 000},
            {name = "Fatshadow", value = 000},
            {name = "Stonefish", value = 000},
            {name = "Yellowhead Brownfish", value = 000},
            {name = "Legfin", value = 000},
            {name = "Flatface", value = 000},
            {name = "Yelloweye Redfish", value = 000},
            {name = "Greenface", value = 000},
            {name = "Pinkfin Bluefish", value = 000},
            {name = "Bluebright", value = 000},
            {name = "Yellowfin Greenfish", value = 000},
            {name = "Redstripe Grayfish", value = 000},
            {name = "Pinkshadow", value = 000},
            {name = "Redhead Slimfish", value = 000},
            {name = "Brightfin", value = 000},
            {name = "Blackhead Bluefish", value = 000},
            {name = "Rosetentacle Octopus", value = 000},
            {name = "Darkfin Fatfish", value = 000},
            {name = "Yellowfin Brownfish", value = 000},
            {name = "Trio Bluefish", value = 000},
            {name = "Redeye Squid", value = 000},
            {name = "Redtentacle Squid", value = 000},
            {name = "Orangecrab", value = 000},
            {name = "Greeneye Shrimp", value = 000},
            {name = "Striped Snail", value = 000},
            {name = "Pinkworm", value = 000},
            {name = "Longfang Insect", value = 000},
			
			{name = "Small Branch", value = 000},
			{name = "Jumbo Shrimp", value = 000},
			{name = "Green Wiggler", value = 000},
			{name = "Pinky Fish", value = 000},
			{name = "Sunny Fish", value = 000},
			{name = "Common Catch", value = 000},
			{name = "Big Common Catch", value = 000},
			{name = "Electric Blue Fish", value = 000},
			{name = "Golden Thread", value = 000},
			{name = "Copper Wire", value = 000},
			{name = "Blue Snail", value = 000},
			{name = "Green Snail Shell", value = 000},
			{name = "Desert Scorpion", value = 000},
			{name = "Volcanic Rocks", value = 000},
			{name = "Light Blue Shell", value = 000},
			{name = "Orange Shell", value = 000},
			{name = "Locked Brown Shell", value = 000},
			{name = "Locked Red and Pink Shell", value = 000},
			{name = "Light Red Shell", value = 000},
			{name = "Caramel Shell", value = 000},
			{name = "Deep Red Shell", value = 000},
			{name = "Warped Brown Stone", value = 000},
			{name = "Monster Tail", value = 000},
			{name = "Bamboo Piece", value = 000},
			{name = "Magikarp Fin", value = 000},
			{name = "Black Gravel", value = 000},
			{name = "Green Orb", value = 000},
			{name = "Brown Wiggler", value = 000},
			{name = "Shiny Green Star", value = 000},
			{name = "Light Blue Gravel", value = 000},
			{name = "Light Pink Stone", value = 000},
			{name = "Light Blue Stone", value = 000},
			{name = "Monster Claw", value = 000},
			{name = "Copper Plate", value = 000},
			{name = "Seaweed Piece", value = 000},
			{name = "Barrel Fragment", value = 000},
			{name = "Yellow Flower", value = 000},
			{name = "Big Blue Flower", value = 000},
			{name = "Large Monster Claw", value = 000},
			{name = "Large Dried Leaf", value = 000},
			{name = "Small Monster Claw", value = 000},
			{name = "Yellow Star", value = 000},
			{name = "Rare Blue Stone", value = 000},
			{name = "Oceanic Blue Stone", value = 000},
			{name = "Green Gravel", value = 000},
			{name = "Spool of Thread", value = 000},
			{name = "Green Sea Slime", value = 000},
			{name = "Cluster of Rare Green Stones", value = 000},
			{name = "Banana Peel", value = 000},
			{name = "Dark Blue Thread", value = 000},
			{name = "Small Shrimp", value = 000},
			{name = "Large Saltwater Shrimp", value = 000},
			{name = "Blue Jellyfish", value = 000},
			{name = "Small Brown Snail", value = 000},
			{name = "Seaweed", value = 000},
			{name = "Large Brown Fish", value = 000},
			{name = "Large Fat Green Fish", value = 000},
			{name = "Yellow Dirt", value = 000},
			{name = "Slowpoke Tail", value = 000},
			{name = "Water Gem", value = 000},
			{name = "seed", value = 000},
			{name = "Dragon Scale", value = 000},
              
            {name = "snowball", value = 000},
            {name = "bottle of poison", value = 000},
            {name = "enchanted gem", value = 000},
            {name = "band aid", value = 000},
            {name = "Thread", value = 000},
            {name = "water pendant", value = 000},
            {name = "Squirrel Nut", value = 000},
            {name = "bone", value = 000},
            {name = "Monster Claw", value = 000},
            {name = "Farfetch'd stick", value = 000},
            {name = "squirtle hull", value = 000},
            {name = "blastoise hull", value = 000},
            {name = "crab claw", value = 000},
            {name = "gyarados tail", value = 000},
            {name = "dragon tail", value = 000},
            {name = "locksmith of shell", value = 000},
            {name = "seahorse tail", value = 000},
            {name = "blue ball", value = 000},
            {name = "giant fin", value = 000},
            {name = "ice bra", value = 000},
            {name = "seal tail", value = 000},
            {name = "strange spike", value = 000},
            {name = "horn", value = 000},
            {name = "fish fin", value = 000},
            {name = "future orb", value = 000},
            {name = "gem star", value = 000},
            {name = "piece of coral", value = 000},
            {name = "psyduck mug", value = 000},
            {name = "karate duck", value = 000},
            {name = "nail", value = 000},
            {name = "red scale", value = 000},
            {name = "point of light", value = 000},
            {name = "wooper horn", value = 000},
            {name = "small tail", value = 000},
            {name = "tentacle", value = 000},
            {name = "streak tail", value = 000},
            {name = "ice orb", value = 000},
            {name = "strange thing", value = 000},
              
            {name = "White Shell", value = 000},
            {name = "Warped Brown Stone", value = 000},
            {name = "stone orb", value = 000},
            {name = "ice orb", value = 000},
            {name = "onix tail", value = 000},
            {name = "giant ruby", value = 000},
            {name = "giant emerald", value = 000},
            {name = "emerald", value = 000},
            {name = "small stone", value = 000},
            {name = "ruby", value = 000},
            {name = "earth ball", value = 000},
              
            {name = "Maritime Trio", value = 000},
            {name = "Oceanic Aurora", value = 000},
            {name = "Deep Emerald", value = 000},
            {name = "Marine Steel", value = 000},
            {name = "Twilight Coral", value = 000},
            {name = "Blue Tide", value = 000},
            {name = "Twin Waves", value = 000},
            {name = "Coral Meteorite", value = 000},
            {name = "Submarine Fire", value = 000},
            {name = "Tide Peak", value = 000},
            {name = "Sea Treasure", value = 000},
            {name = "King's Crown", value = 000},
		},
	},
}

skillSmithingInfos = {
	banner = "ferreiro",
	width = 237,
	firstPanel = function() doSetupSmithingPanel("ores") end,
	buttons = {
		{icon = "minerios", iconType = "IMAGE", name = "Ores", action = function() doSetupSmithingPanel("ores") end},
		{icon = 357, iconType = "ITEM", name = "Tools", width = 127, action = function() doSetupSmithingPanel("tools") end},
	},
	panel = {
		ores = {
			{level = 1, name = "Copper Ore", pick = "Old Pickaxe"},
			{level = 1, name = "Tin Ore", pick = "Old Pickaxe"},
			{level = 15, name = "Iron Ore", pick = "Old Pickaxe"},
			{level = 25, name = "Silver Ore", pick = "Old Pickaxe"},
			{level = 33, name = "Coal Ore", pick = "Old Pickaxe"},
			{level = 40, name = "Gold Ore", pick = "Good Pickaxe"},
		},
		tools = {
			{level = 1, name = "Old Pickaxe"},
			{level = 20, name = "Good Pickaxe"},
			{level = 40, name = "Super Pickaxe"},
		},
		
	},
}

skillWoodcuttingInfos = {
	banner = "carpinteiro",
	width = 222,
	firstPanel = function() doSetupWoodcuttingPanel("woods") end,
	buttons = {
		{icon = 16884, iconType = "ITEM", name = "Woods", width = 90, action = function() doSetupWoodcuttingPanel("woods") end},
		{icon = 16870, iconType = "ITEM", name = "Tools", width = 127, action = function() doSetupWoodcuttingPanel("tools") end},
	},
	panel = {
		woods = {
			{level = 1, name = "Normal Log", pick = "Old Axe"},
			{level = 12, name = "Oak Log", pick = "Old Axe"},
			{level = 26, name = "Willow Log", pick = "Old Axe"},
			{level = 40, name = "Maple Log", pick = "Old Axe"},
			{level = 50, name = "Teak Log", pick = "Good Axe"},
		},
		tools = {
			{level = 1, name = "Old Axe"},
			{level = 20, name = "Good Axe"},
			{level = 40, name = "Super Axe"},
		},
	},
}


skillConstructionInfos = {
	banner = "arquiteto",
	width = 316,
	firstPanel = function() doSetupConstructionPanel("planks") end,
	buttons = {
		{icon = 16884, iconType = "ITEM", name = "Planks", width = 93, action = function() doSetupConstructionPanel("planks") end},
		{icon = 16870, iconType = "ITEM", name = "Mobile", width = 93, action = function() doSetupConstructionPanel("mobile") end},
		{icon = 16870, iconType = "ITEM", name = "Others", width = 93, action = function() doSetupConstructionPanel("others") end},
	},
	panel = {
		planks = {
			{level = 1, name = "Normal Plank", required = { {"Normal Log", 1} }},
			{level = 12, name = "Oak Plank", required = { {"Oak Log", 1} }},
			{level = 26, name = "Willow Plank", required = { {"Willow Log", 1} }},
			{level = 40, name = "Maple Plank", required = { {"Maple Log", 1} }},
			{level = 50, name = "Teak Plank", required = { {"Teak Log", 1} }},
		},
		mobile = {
			{level = 2, name = "Wooden Chair", required = { {"Normal Plank", 2}, {"Bronze Nail", 2} }},
			{level = 3, name = "Dresser", required = { {"Normal Plank", 3}, {"Bronze Nail", 3} }},
			{level = 5, name = "Wooden Table", required = { {"Normal Plank", 4}, {"Bronze Nail", 4} }},
			{level = 7, name = "Wardrobe", required = { {"Normal Plank", 7}, {"Bronze Nail", 7} }},
			{level = 9, name = "Pendulum Clock", required = { {"Normal Plank", 10}, {"Bronze Nail", 10} }},
			{level = 11, name = "Wooden Balcony", required = { {"Normal Plank", 12}, {"Bronze Nail", 12} }},
			{level = 13, name = "Oak Chair", required = { {"Oak Plank", 2}, {"Iron Nail", 2} }},
			{level = 15, name = "Oak Dresser", required = { {"Oak Plank", 3}, {"Iron Nail", 3} }},
			{level = 17, name = "Oak Table", required = { {"Oak Plank", 4}, {"Iron Nail", 4} }},
			{level = 18, name = "Rustic Oak Chair", required = { {"Oak Plank", 4}, {"Iron Nail", 4} }},
			{level = 20, name = "Box", required = { {"Oak Plank", 5}, {"Iron Nail", 5} }},
			{level = 21, name = "Oak Wardrobe", required = { {"Oak Plank", 7}, {"Iron Nail", 7} }},
			{level = 22, name = "Strong Oak Table", required = { {"Oak Plank", 8}, {"Iron Nail", 8} }},
			{level = 23, name = "Oak Pendulum Clock", required = { {"Oak Plank", 10}, {"Iron Nail", 10} }},
			{level = 25, name = "Oak Balcony", required = { {"Oak Plank", 12}, {"Iron Nail", 12} }},
			{level = 27, name = "Jungle Balcony", required = { {"Oak Plank", 16}, {"Iron Nail", 16}, {"Leaves", 8} }},
			{level = 28, name = "Willow Chair", required = { {"Willow Plank", 2}, {"Iron Nail", 2} }},
			{level = 30, name = "Willow Dresser", required = { {"Willow Plank", 3}, {"Iron Nail", 3} }},
			{level = 32, name = "Willow Table", required = { {"Willow Plank", 4}, {"Iron Nail", 4} }},
			{level = 33, name = "Rustic Willow Chair", required = { {"Willow Plank", 4}, {"Iron Nail", 4} }},
			{level = 35, name = "Willow Wardrobe", required = { {"Willow Plank", 7}, {"Iron Nail", 7} }},
			{level = 36, name = "Strong Willow Table", required = { {"Willow Plank", 8}, {"Iron Nail", 8} }},
			{level = 37, name = "Willow Cushion Chair", required = { {"Willow Plank", 8}, {"Iron Nail", 8}, {"Cotton", 4} }},
			{level = 39, name = "Willow Pendulum Clock", required = { {"Willow Plank", 10}, {"Iron Nail", 10} }},
			{level = 41, name = "Willow Balcony", required = { {"Willow Plank", 12}, {"Iron Nail", 12} }},
			{level = 43, name = "Willow Jungle Balcony", required = { {"Willow Plank", 16}, {"Iron Nail", 16}, {"Leaves", 16} }},
			{level = 44, name = "Maple Chair", required = { {"Maple Plank", 2}, {"Steel Nail", 2} }},
			{level = 46, name = "Maple Dresser", required = { {"Maple Plank", 3}, {"Steel Nail", 3} }},
			{level = 47, name = "Maple Table", required = { {"Maple Plank", 4}, {"Steel Nail", 4} }},
			{level = 49, name = "Rustic Maple Chair", required = { {"Maple Plank", 4}, {"Steel Nail", 4} }},
			{level = 50, name = "Maple Wardrobe", required = { {"Maple Plank", 7}, {"Steel Nail", 7} }},
			{level = 51, name = "Strong Maple Table", required = { {"Maple Plank", 8}, {"Steel Nail", 8} }},
			{level = 52, name = "Maple Cushion Chair", required = { {"Maple Plank", 8}, {"Steel Nail", 8}, {"Cotton", 8} }},
			{level = 55, name = "Maple Pendulum Clock", required = { {"Maple Plank", 10}, {"Steel Nail", 10} }},
			{level = 58, name = "Maple Balcony", required = { {"Maple Plank", 12}, {"Steel Nail", 12} }},
			{level = 60, name = "Maple Jungle Balcony", required = { {"Maple Plank", 16}, {"Steel Nail", 16} }}
		},
		others = {
			{level = 1, name = "Cotton", required = { {"Wool Ball", 1} }},
			{level = 1, name = "Cotton", required = { {"Sheep Wool", 1} }}
		},
	},
}

skillMiningInfos = {
	banner = "mineiro",
	firstPanel = function() doSetupMiningPanel("bars") end,
	buttons = {
		{icon = 16079, iconType = "ITEM", name = "Barras", width = 93, action = function() doSetupMiningPanel("bars") end},
		{icon = 3459, iconType = "ITEM", name = "Tools", width = 127, action = function() doSetupMiningPanel("tools") end},
		{icon = 16942, iconType = "ITEM", name = "Others", width = 93, action = function() doSetupMiningPanel("others") end},
	},
	panel = {
		bars = {
			{level = 1, name = "Bronze Bar", required = { {"Copper Ore", 1}, {"Tin Ore", 1} }},
			{level = 15, name = "Iron Bar", required = { {"Iron Ore", 1} }},
			{level = 25, name = "Silver Bar", required = { {"Silver Ore", 1}, {"Coal Ore", 1} }},
			{level = 30, name = "Steel Bar", required = { {"Iron Ore", 1}, {"Coal Ore", 1} }},
			{level = 40, name = "Gold Bar", required = { {"Gold Ore", 1}, {"Coal Ore", 1} }}
		},
		tools = {
			{level = 4, name = "Old Hammer", required = { {"Bronze Bar", 1}, {"Normal Log", 2} }},
			{level = 6, name = "Work Knife", required = { {"Bronze Bar", 1}, {"Normal Log", 3} }},
			{level = 8, name = "Old Axe", required = { {"Bronze Bar", 4}, {"Normal Log", 4} }},
			{level = 11, name = "Old Pickaxe", required = { {"Bronze Bar", 6}, {"Normal Log", 6} }},
			{level = 15, name = "Saw", required = { {"Iron Bar", 8}, {"Oak Log", 8} }},
			{level = 28, name = "Good Rod", required = { {"Iron Bar", 10}, {"Oak Plank", 10}, {"Thread", 50} }},
			{level = 30, name = "Good Hammer", required = { {"Iron Bar", 10}, {"Oak Log", 10} }},
			{level = 31, name = "Good Axe", required = { {"Iron Bar", 10}, {"Oak Log", 10} }},
			{level = 34, name = "Good Pickaxe", required = { {"Iron Bar", 12}, {"Oak Plank", 12} }},
			{level = 55, name = "Super Axe", required = { {"Steel Bar", 12}, {"Gold Bar", 12} }},
			{level = 58, name = "Super Pickaxe", required = { {"Steel Bar", 18}, {"Gold Bar", 18} }}
		},
		others = {
			{level = 1, name = "Bronze Nail", required = { {"Bronze Bar", 1} }},
			{level = 15, name = "Iron Nail", required = { {"Iron Bar", 1} }},
			{level = 30, name = "Steel Nail", required = { {"Steel Bar", 1} }},
			{level = 30, name = "Metal Thread", required = { {"Steel Bar", 1}, {"Thread", 10} }}
		},
	},
}


profileBorders = {	
	{type = "NONE"},
	{type = "VIP", requireDesc = "Available to VIP players", image = "vip", name = "Vip", required = "None", level = "1", desc = "This edge is a symbol of distinction, available to all VIP players."},
	{type = "VIPPLUS", requireDesc = "Available to VIP Plus players", image = "vip_plus", name = "Vip Plus", required = "None", level = "1", desc = "This edge is a symbol of status and prestige, available to players who have Vip Plus."},
	
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 50", image = "level_1", name = "Beginner Trainer", level = "50", desc = "You have taken your first steps in the Pokémon world. Continue the journey to discover and learn more about Pokémon."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 100", image = "level_2", name = "Intermediate Trainer", level = "100", desc = "You are becoming a skilled trainer. Your experience in Pokémon battles is starting to show."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 190", image = "level_3", name = "Advanced Trainer", level = "190", desc = "With great knowledge and skill, you have become an advanced trainer. Your journey is just beginning."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 250", image = "level_4", name = "Experienced Trainer", level = "250", desc = "Your experience in Pokémon battles is evident. You have the ability to face difficult challenges."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 300", image = "level_5", name = "Senior Trainer", level = "300", desc = "You have reached a level of respect among trainers. Your wisdom and experience are an inspiration to others."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 375", image = "level_6", name = "Master Trainer", level = "375", desc = "You have mastered the art of training Pokémon. Your skill is recognized throughout the Pokémon world."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 400", image = "level_7", name = "Grandmaster Trainer", level = "400", desc = "You have reached a level of mastery rarely seen. You are a legend among Pokémon trainers."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 450", image = "level_8", name = "Elite Trainer", level = "450", desc = "You are among the elite of Pokémon trainers. Your skill and experience are unmatched."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 500", image = "level_9", name = "Elite-Master Trainer", level = "500", desc = "You have reached the pinnacle of Pokémon training. You are an inspiration to all trainers."},
	{type = "LEVEL", requireDesc = "Acquired upon reaching level 600", image = "level_10", name = "Legendary Trainer", level = "600", desc = "You have become a legend in the Pokémon world. Your journey is a story told to inspire future trainers."},
	
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 100 tournaments", image = "tornament_1", name = "Competitor Trainer", level = "100", desc = "You are standing out in the world of Pokémon tournaments. Continue to compete and hone your skills."},
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 500 tournaments", image = "tornament_2", name = "Winner Trainer", level = "500", desc = "Your ability to win tournaments is impressive. You are becoming a true competitor in the Pokémon world."},
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 1.000 tournaments", image = "tornament_3", name = "Champion Trainer", level = "1000", desc = "With a thousand tournament victories, you have become a champion. Your determination and skill are admirable."},
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 2.000 tournaments", image = "tornament_4", name = "Elite Trainer", level = "2000", desc = "You have reached the elite of Pokémon tournament trainers. Your experience and skill are unmatched."},
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 3.500 tournaments", image = "tornament_5", name = "Legendary Trainer", level = "3500", desc = "You have become a legend in Pokémon tournaments. Your journey is a story told to inspire future competitors."},
	{type = "TORNAMENT", requireDesc = "Acquired by participating in 5.000 tournaments", image = "tornament_6", name = "Supreme Trainer", level = "5000", desc = "You have reached the pinnacle of Pokémon tournaments. You are an inspiration to all trainers."},
	
	{type = "FENIX", requireDesc = "Acquired in server return package", image = "felix", name = "Phoenix Return", required = "None", level = "1", desc = "This edge is a symbol of renewal and resilience, acquired in the server's return package."},
}

