pokemonThingsPositionLocal = {
	["Bulbasaur"] = {size = 90, animated = false, top = -6, left = -7, base = "grass"},
	["Ivysaur"] = {size = 90, animated = false, top = -6, left = -7, base = "grass"},
	["Venusaur"] = {size = 90, animated = false, top = -1, left = 7, base = "grass"},
	["Charmander"] = {size = 90, animated = false, top = -6, left = -7, base = "fire"},
	["Charmeleon"] = {size = 90, animated = false, top = -6, left = -7, base = "fire"},
	["Charizard"] = {size = 90, animated = false, top = -8, left = 7, base = "fire"},
	["Squirtle"] = {size = 90, animated = false, top = -6, left = -7, base = "water"},
	["Wartortle"] = {size = 90, animated = false, top = -6, left = -7, base = "water"},
	["Blastoise"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Caterpie"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Metapod"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Butterfree"] = {size = 90, animated = true, top = -3, left = -3, base = "normal"},
	["Weedle"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Kakuna"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Beedrill"] = {size = 90, animated = true, top = -3, left = 0, base = "normal"},
	["Pidgey"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Pidgeotto"] = {size = 90, animated = false, top = -8, left = 2, base = "normal"},
	["Pidgeot"] = {size = 90, animated = false, top = -8, left = 29, base = "normal"},
	["Rattata"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Raticate"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Spearow"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Fearow"] = {size = 90, animated = true, top = -6, left = 11, base = "normal"},
	["Ekans"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Arbok"] = {size = 90, animated = false, top = 0, left = 10, base = "normal"},
	["Pikachu"] = {size = 90, animated = false, top = -6, left = -11, base = "normal"},
	["Raichu"] = {size = 90, animated = false, top = -11, left = -5, base = "normal"},
	["Sandshrew"] = {size = 90, animated = false, top = -6, left = -5, base = "ground"},
	["Sandslash"] = {size = 90, animated = false, top = -11, left = -7, base = "ground"},
	["Nidoran Female"] = {size = 90, animated = false, top = -6, left = -9, base = "normal"},
	["Nidorina"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Nidoqueen"] = {size = 90, animated = false, top = -7, left = 2, base = "normal"},
	["Nidoran Male"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Nidorino"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Nidoking"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	["Clefairy"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Clefable"] = {size = 90, animated = false, top = -6, left = -3, base = "normal"},
	["Vulpix"] = {size = 90, animated = false, top = -6, left = -5, base = "fire"},
	["Ninetales"] = {size = 90, animated = false, top = 1, left = 8, base = "fire"},
	["Jigglypuff"] = {size = 90, animated = false, top = -8, left = -5, base = "normal"},
	["Wigglytuff"] = {size = 90, animated = false, top = -9, left = -6, base = "normal"},
	["Zubat"] = {size = 90, animated = true, top = -10, left = -5, base = "dark_forest"},
	["Golbat"] = {size = 90, animated = true, top = -7, left = 8, base = "dark_forest"},
	["Oddish"] = {size = 90, animated = false, top = -8, left = -14, base = "grass"},
	["Gloom"] = {size = 90, animated = false, top = -8, left = -9, base = "grass"},
	["Vileplume"] = {size = 90, animated = false, top = -8, left = 1, base = "grass"},
	["Paras"] = {size = 90, animated = false, top = -2, left = -7, base = "grass"},
	["Parasect"] = {size = 90, animated = false, top = -6, left = 1, base = "grass"},
	["Venonat"] = {size = 90, animated = false, top = -6, left = -9, base = "grass"},
	["Venomoth"] = {size = 90, animated = true, top = -2, left = 2, base = "grass"},
	["Diglett"] = {size = 90, animated = false, top = -6, left = -7, base = "ground"},
	["Dugtrio"] = {size = 90, animated = false, top = -6, left = -4, base = "ground"},
	["Meowth"] = {size = 90, animated = false, top = -6, left = -6, base = "normal"},
	["Persian"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Psyduck"] = {size = 90, animated = false, top = -6, left = -7, base = "water"},
	["Golduck"] = {size = 90, animated = false, top = -8, left = 2, base = "water"},
	["Mankey"] = {size = 90, animated = false, top = -6, left = -6, base = "fighting"},
	["Primeape"] = {size = 90, animated = false, top = -6, left = 13, base = "fighting"},
	["Growlithe"] = {size = 90, animated = false, top = -6, left = -11, base = "fire"},
	["Arcanine"] = {size = 90, animated = false, top = -4, left = 12, base = "fire"},
	["Poliwag"] = {size = 90, animated = false, top = -2, left = -6, base = "water"},
	["Poliwhirl"] = {size = 90, animated = false, top = -6, left = -4, base = "water"},
	["Poliwrath"] = {size = 90, animated = false, top = -6, left = 2, base = "water"},
	["Abra"] = {size = 90, animated = false, top = -10, left = -6, base = "psychic"},
	["Kadabra"] = {size = 90, animated = false, top = -4, left = -4, base = "psychic"},
	["Alakazam"] = {size = 90, animated = false, top = -9, left = -6, base = "psychic"},
	["Machop"] = {size = 90, animated = false, top = -7, left = -11, base = "fighting"},
	["Machoke"] = {size = 90, animated = false, top = -8, left = -1, base = "fighting"},
	["Machamp"] = {size = 90, animated = false, top = -8, left = 6, base = "fighting"},
	["Bellsprout"] = {size = 90, animated = false, top = -9, left = -11, base = "grass"},
	["Weepinbell"] = {size = 90, animated = false, top = -8, left = -7, base = "grass"},
	["Victreebel"] = {size = 90, animated = false, top = -8, left = 2, base = "grass"},
	["Tentacool"] = {size = 90, animated = true, top = -8, left = -8, base = "water"},
	["Tentacruel"] = {size = 90, animated = true, top = -8, left = 6, base = "water"},
	["Geodude"] = {size = 90, animated = false, top = 2, left = -1, base = "rock"},
	["Graveler"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	["Golem"] = {size = 90, animated = false, top = -8, left = 4, base = "rock"},
	["Ponyta"] = {size = 90, animated = false, top = -8, left = -7, base = "fire"},
	["Rapidash"] = {size = 90, animated = false, top = -8, left = 5, base = "fire"},
	["Slowpoke"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Slowbro"] = {size = 90, animated = false, top = -8, left = -5, base = "water"},
	["Magnemite"] = {size = 90, animated = true, top = -2, left = -6, base = "normal"},
	["Magneton"] = {size = 90, animated = true, top = -10, left = -2, base = "normal"},
	["Farfetch'd"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	["Doduo"] = {size = 90, animated = false, top = -8, left = -2, base = "normal"},
	["Dodrio"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Seel"] = {size = 90, animated = false, top = -4, left = -2, base = "ice"},
	["Dewgong"] = {size = 90, animated = false, top = -2, left = 4, base = "ice"},
	["Grimer"] = {size = 90, animated = false, top = -3, left = -3, base = "dark_forest"},
	["Muk"] = {size = 90, animated = false, top = -4, left = 7, base = "dark_forest"},
	["Shellder"] = {size = 90, animated = false, top = -4, left = -8, base = "ice"},
	["Cloyster"] = {size = 90, animated = false, top = -4, left = 5, base = "ice"},
	["Gastly"] = {size = 90, animated = true, top = -8, left = -7, base = "ghost"},
	["Haunter"] = {size = 90, animated = false, top = -8, left = -7, base = "ghost"},
	["Gengar"] = {size = 90, animated = false, top = -8, left = -2, base = "ghost"},
	["Onix"] = {size = 85, animated = false, top = 0, left = 4, base = "rock"},
	["Drowzee"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},
	["Hypno"] = {size = 90, animated = false, top = -8, left = -4, base = "psychic"},
	["Krabby"] = {size = 90, animated = false, direction = 1, top = -8, left = -9, base = "water"},
	["Kingler"] = {size = 90, animated = false, direction = 3, top = -8, left = 6, base = "water"},
	["Voltorb"] = {size = 90, animated = false, top = -4, left = -7, base = "normal"},
	["Electrode"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Exeggcute"] = {size = 90, animated = true, top = -5, left = -2, base = "grass"},
	["Exeggutor"] = {size = 90, animated = false, top = -6, left = 2, base = "grass"},
	["Cubone"] = {size = 90, animated = false, top = -8, left = -10, base = "ground"},
	["Marowak"] = {size = 90, animated = false, top = -8, left = -7, base = "ground"},
	["Hitmonlee"] = {size = 90, animated = false, top = -8, left = 2, base = "fighting"},
	["Hitmonchan"] = {size = 90, animated = false, top = -8, left = -7, base = "fighting"},
	["Lickitung"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Koffing"] = {size = 90, animated = true, top = -8, left = 2, base = "dark_forest"},
	["Weezing"] = {size = 90, animated = true, top = 9, left = 15, base = "dark_forest"},
	["Rhyhorn"] = {size = 90, animated = false, top = -8, left = -2, base = "rock"},
	["Rhydon"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	["Chansey"] = {size = 90, animated = false, top = -5, left = -2, base = "normal"},
	["Tangela"] = {size = 90, animated = false, top = -8, left = -7, base = "grass"},
	["Kangaskhan"] = {size = 90, animated = false, top = -4, left = 1, base = "normal"},
	["Horsea"] = {size = 90, animated = false, top = -2, left = -7, base = "water"},
	["Seadra"] = {size = 90, animated = false, top = -5, left = -1, base = "water"},
	["Goldeen"] = {size = 90, animated = true, top = -8, left = -7, base = "water"},
	["Seaking"] = {size = 90, animated = true, top = -8, left = -7, base = "water"},
	["Staryu"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Starmie"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Mr. Mime"] = {size = 90, animated = false, top = -8, left = -2, base = "psychic"},
	["Scyther"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Jynx"] = {size = 90, animated = false, top = -8, left = -5, base = "ice"},
	["Electabuzz"] = {size = 90, animated = false, top = -6, left = -1, base = "normal"},
	["Magmar"] = {size = 90, animated = false, top = -6, left = 1, base = "fire"},
	["Pinsir"] = {size = 90, animated = false, top = -6, left = 1, base = "normal"},
	["Tauros"] = {size = 90, animated = false, top = -5, left = -6, base = "normal"},
	["Magikarp"] = {size = 90, animated = true, top = -8, left = -7, base = "water"},
	["Gyarados"] = {size = 90, animated = false, top = -5, left = 4, base = "water"},
	["Lapras"] = {size = 90, animated = false, top = -8, left = 11, base = "ice"},
	["Ditto"] = {size = 90, animated = false, top = -6, left = -11, base = "normal"},
	["Eevee"] = {size = 90, animated = false, top = -6, left = -10, base = "normal"},
	["Vaporeon"] = {size = 90, animated = false, top = -6, left = -4, base = "water"},
	["Jolteon"] = {size = 90, animated = false, top = -6, left = -6, base = "normal"},
	["Flareon"] = {size = 90, animated = false, top = -6, left = -4, base = "fire"},
	["Porygon"] = {size = 90, animated = false, top = -4, left = -7, base = "psychic"},
	["Omanyte"] = {size = 90, animated = false, top = -4, left = -7, base = "water"},
	["Omastar"] = {size = 90, animated = false, top = -4, left = -7, base = "water"},
	["Kabuto"] = {size = 90, animated = false, top = -4, left = -6, base = "water"},
	["Kabutops"] = {size = 90, animated = false, top = -4, left = 1, base = "water"},
	["Aerodactyl"] = {size = 80, animated = true, top = 8, left = 30, base = "normal"},
	["Snorlax"] = {size = 90, animated = false, top = -6, left = 1, base = "normal"},
	["Articuno"] = {size = 90, animated = true, top = 1, left = 25, base = "ice"},
	["Zapdos"] = {size = 90, animated = true, top = -3, left = 25, base = "normal"},
	["Moltres"] = {size = 90, animated = true, top = 3, left = 47, base = "fire"},
	["Dratini"] = {size = 90, animated = false, top = -8, left = -10, base = "normal"},
	["Dragonair"] = {size = 90, animated = false, top = -2, left = -2, base = "normal"},
	["Dragonite"] = {size = 90, animated = false, top = -6, left = 12, base = "normal"},
	["Mewtwo"] = {size = 90, animated = false, top = -8, left = -4, base = "psychic"},
	["Mew"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},

	["Chikorita"] = {size = 90, animated = false, top = -4, left = -7, base = "grass"},
	["Bayleef"] = {size = 90, animated = false, top = -4, left = -7, base = "grass"},
	["Meganium"] = {size = 90, animated = false, top = -4, left = -2, base = "grass"},
	["Cyndaquil"] = {size = 90, animated = false, top = -8, left = -7, base = "fire"},
	["Quilava"] = {size = 90, animated = false, top = -4, left = -7, base = "fire"},
	["Typhlosion"] = {size = 90, animated = false, top = -4, left = 2, base = "fire"},
	["Totodile"] = {size = 90, animated = false, top = -4, left = -5, base = "water"},
	["Croconaw"] = {size = 90, animated = false, top = -4, left = -3, base = "water"},
	["Feraligatr"] = {size = 90, animated = false, top = -4, left = 2, base = "water"},
	["Sentret"] = {size = 90, animated = false, top = -8, left = -4, base = "normal"},
	["Furret"] = {size = 90, animated = false, top = -8, left = -13, base = "normal"},
	["Hoothoot"] = {size = 90, animated = false, top = -8, left = -9, base = "normal"},
	["Noctowl"] = {size = 90, animated = false, top = -8, left = 6, base = "normal"},
	["Ledyba"] = {size = 90, animated = true, top = -8, left = -5, base = "normal"},
	["Ledian"] = {size = 90, animated = true, top = -8, left = -6, base = "normal"},
	["Spinarak"] = {size = 90, animated = false, top = -8, left = -10, base = "normal"},
	["Ariados"] = {size = 90, animated = false, top = -2, left = 0, base = "normal"},
	["Crobat"] = {size = 90, animated = true, top = -8, left = 4, base = "dark_forest"},
	["Chinchou"] = {size = 90, animated = false, top = -8, left = -4, base = "water"},
	["Lanturn"] = {size = 90, animated = true, top = -8, left = -9, base = "water"},
	["Pichu"] = {size = 90, animated = false, top = -4, left = -12, base = "normal"},
	["Cleffa"] = {size = 90, animated = false, top = -4, left = -8, base = "normal"},
	["Igglybuff"] = {size = 90, animated = false, top = -4, left = -12, base = "normal"},
	["Togepi"] = {size = 90, animated = false, top = -4, left = -10, base = "normal"},
	["Togetic"] = {size = 90, animated = false, top = -8, left = -10, base = "normal"},
	["Natu"] = {size = 90, animated = false, top = -4, left = -9, base = "psychic"},
	["Xatu"] = {size = 90, animated = false, top = -4, left = -7, base = "psychic"},
	["Mareep"] = {size = 90, animated = false, top = -8, left = -13, base = "normal"},
	["Flaaffy"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Ampharos"] = {size = 90, animated = false, top = -8, left = -4, base = "normal"},
	["Bellossom"] = {size = 90, animated = false, top = -4, left = -12, base = "grass"},
	["Marill"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Azumarill"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Sudowoodo"] = {size = 90, animated = false, top = -8, left = -2, base = "normal"},
	["Politoed"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Hoppip"] = {size = 90, animated = true, top = -8, left = -5, base = "grass"},
	["Skiploom"] = {size = 90, animated = false, top = -8, left = -7, base = "grass"},
	["Jumpluff"] = {size = 90, animated = false, top = -8, left = -5, base = "grass"},
	["Aipom"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	["Sunkern"] = {size = 90, animated = true, top = -4, left = -9, base = "grass"},
	["Sunflora"] = {size = 90, animated = false, top = -4, left = -7, base = "grass"},
	["Yanma"] = {size = 90, animated = true, top = -8, left = 1, base = "normal"},
	["Wooper"] = {size = 90, animated = false, top = -4, left = -7, base = "water"},
	["Quagsire"] = {size = 90, animated = false, top = -8, left = -11, base = "water"},
	["Espeon"] = {size = 90, animated = false, top = -4, left = -4, base = "psychic"},
	["Umbreon"] = {size = 90, animated = false, top = -4, left = -9, base = "ghost"},
	["Murkrow"] = {size = 90, animated = false, top = -8, left = -4, base = "ghost"},
	["Slowking"] = {size = 90, animated = false, top = -6, left = -7, base = "psychic"},
	["Misdreavus"] = {size = 90, animated = true, top = -8, left = -7, base = "ghost"},
	["Unown"] = {size = 90, animated = true, top = -8, left = -7, base = "psychic"},
	["Wobbuffet"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},
	["Girafarig"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},
	["Pineco"] = {size = 90, animated = true, top = -8, left = -12, base = "normal"},
	["Forretress"] = {size = 90, animated = true, top = -8, left = 1, base = "normal"},
	["Dunsparce"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Gligar"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Steelix"] = {size = 75, animated = false, top = 10, left = 17, base = "rock"},
	["Snubbull"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Granbull"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Qwilfish"] = {size = 90, animated = true, top = -8, left = -7, base = "water"},
	["Scizor"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Shuckle"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Heracross"] = {size = 90, animated = false, top = -8, left = -1, base = "grass"},
	["Sneasel"] = {size = 90, animated = false, top = -8, left = -12, base = "ice"},
	["Teddiursa"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Ursaring"] = {size = 90, animated = false, top = -8, left = 2, base = "normal"},
	["Slugma"] = {size = 90, animated = false, top = -4, left = -7, base = "fire"},
	["Magcargo"] = {size = 90, animated = false, top = -2, left = -2, base = "fire"},
	["Swinub"] = {size = 90, animated = false, top = -4, left = -10, base = "normal"},
	["Piloswine"] = {size = 90, animated = false, top = -8, left = -4, base = "ice"},
	["Corsola"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Remoraid"] = {size = 90, animated = true, top = -4, left = -12, base = "water"},
	["Octillery"] = {size = 90, animated = false, top = -4, left = -7, base = "water"},
	["Delibird"] = {size = 90, animated = false, top = -8, left = -7, base = "ice"},
	["Mantine"] = {size = 90, animated = true, top = -2, left = 15, base = "water"},
	["Skarmory"] = {size = 90, animated = false, top = -8, left = 10, base = "normal"},
	["Houndour"] = {size = 90, animated = false, top = -8, left = -12, base = "fire"},
	["Houndoom"] = {size = 90, animated = false, top = -8, left = 0, base = "fire"},
	["Kingdra"] = {size = 90, animated = false, top = -8, left = -5, base = "water"},
	["Phanpy"] = {size = 90, animated = false, top = -8, left = -10, base = "ground"},
	["Donphan"] = {size = 90, animated = false, top = -8, left = 6, base = "ground"},
	["Porygon2"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},
	["Stantler"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Smeargle"] = {size = 90, animated = false, top = -8, left = -5, base = "normal"},
	["Tyrogue"] = {size = 90, animated = false, top = -8, left = -7, base = "fighting"},
	["Hitmontop"] = {size = 90, animated = false, top = -8, left = -8, base = "fighting"},
	["Smoochum"] = {size = 90, animated = false, top = -4, left = -9, base = "psychic"},
	["Elekid"] = {size = 90, animated = false, top = -4, left = -1, base = "normal"},
	["Magby"] = {size = 90, animated = false, top = -4, left = -10, base = "fire"},
	["Miltank"] = {size = 90, animated = false, top = -6, left = -2, base = "normal"},
	["Blissey"] = {size = 90, animated = false, top = -6, left = -3, base = "normal"},
	["Raikou"] = {size = 90, animated = false, top = -8, left = 14, base = "normal"},
	["Entei"] = {size = 90, animated = false, top = -8, left = 14, base = "fire"},
	["Suicune"] = {size = 90, animated = false, top = -8, left = 14, base = "water"},
	["Larvitar"] = {size = 90, animated = false, top = -8, left = -12, base = "rock"},
	["Pupitar"] = {size = 90, animated = false, top = -8, left = -8, base = "rock"},
	["Tyranitar"] = {size = 90, animated = false, top = -2, left = 6, base = "rock"},
	["Lugia"] = {size = 60, animated = false, top = 28, left = 45, base = "water"},
	["Ho-oh"] = {size = 70, animated = true, top = 18, left = 35, base = "grass"},
	["Celebi"] = {size = 90, animated = true, top = -8, left = -12, base = "grass"},
	
	
	["Treecko"] = {size = 90, animated = false, top = -8, left = -7, base = "grass"},
	["Grovyle"] = {size = 90, animated = false, top = -4, left = 3, base = "grass"},
	["Sceptile"] = {size = 90, animated = false, top = -8, left = -3, base = "grass"},
	["Torchic"] = {size = 90, animated = false, top = -8, left = -7, base = "fire"},
	["Combusken"] = {size = 90, animated = false, top = -8, left = -10, base = "fire"},
	["Blaziken"] = {size = 90, animated = false, top = -4, left = -3, base = "fire"},
	["Mudkip"] = {size = 90, animated = false, top = -4, left = -8, base = "water"},
	["Marshtomp"] = {size = 90, animated = false, top = -4, left = -5, base = "water"},
	["Swampert"] = {size = 90, animated = false, top = -6, left = -1, base = "water"},
	["Poochyena"] = {size = 90, animated = false, top = -8, left = -8, base = "ghost"},
	["Mightyena"] = {size = 90, animated = false, top = -8, left = 9, base = "ghost"},
	["Zigzagoon"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	["Linoone"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	["Wurmple"] = {size = 90, animated = false, top = -8, left = -16, base = "normal"},
	["Silcoon"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Beautifly"] = {size = 90, animated = true, top = -8, left = 10, base = "normal"},
	["Cascoon"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Dustox"] = {size = 90, animated = true, top = -8, left = 0, base = "grass"},
	["Lotad"] = {size = 90, animated = false, top = -4, left = -8, base = "water"},
	["Lombre"] = {size = 90, animated = false, top = -4, left = -9, base = "water"},
	["Ludicolo"] = {size = 90, animated = false, top = -4, left = -3, base = "water"},
	["Seedot"] = {size = 90, animated = false, top = -4, left = -10, base = "grass"},
	["Nuzleaf"] = {size = 90, animated = false, top = -4, left = -5, base = "grass"},
	["Shiftry"] = {size = 90, animated = false, top = -4, left = 8, base = "grass"},
	["Taillow"] = {size = 90, animated = false, top = -8, left = -6, base = "normal"},
	["Swellow"] = {size = 90, animated = false, top = -8, left = 15, base = "normal"},
	["Wingull"] = {size = 90, animated = true, top = -8, left = -3, base = "normal"},
	["Pelipper"] = {size = 90, animated = true, top = -8, left = 10, base = "normal"},
	["Ralts"] = {size = 90, animated = false, top = -8, left = -9, base = "psychic"},
	["Kirlia"] = {size = 90, animated = false, top = -8, left = -8, base = "psychic"},
	["Gardevoir"] = {size = 90, animated = false, top = -4, left = -2, base = "psychic"},
	["Surskit"] = {size = 90, animated = false, top = -8, left = -10, base = "water"},
	["Masquerain"] = {size = 90, animated = true, top = -8, left = 2, base = "grass"},
	["Shroomish"] = {size = 90, animated = false, top = -8, left = -14, base = "grass"},
	["Breloom"] = {size = 90, animated = false, top = -8, left = -7, base = "grass"},
	["Slakoth"] = {size = 90, animated = false, top = -8, left = -9, base = "fighting"},
	["Vigoroth"] = {size = 90, animated = false, top = -8, left = -2, base = "fighting"},
	["Slaking"] = {size = 90, animated = false, top = -8, left = 2, base = "fighting"},
	["Nincada"] = {size = 90, animated = false, top = -8, left = -11, base = "normal"},
	["Ninjask"] = {size = 90, animated = true, top = -8, left = -4, base = "normal"},
	["Shedinja"] = {size = 90, animated = true, top = -8, left = -6, base = "normal"},
	["Whismur"] = {size = 90, animated = false, top = -8, left = -9, base = "normal"},
	["Loudred"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Exploud"] = {size = 90, animated = false, top = -4, left = 5, base = "normal"},
	["Makuhita"] = {size = 90, animated = false, top = -8, left = -9, base = "fighting"},
	["Hariyama"] = {size = 90, animated = false, top = -4, left = 16, base = "fighting"},
	["Azurill"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Nosepass"] = {size = 90, animated = false, top = -8, left = -14, base = "rock"},
	["Skitty"] = {size = 90, animated = false, top = -8, left = -14, base = "normal"},
	["Delcatty"] = {size = 90, animated = false, top = -8, left = -2, base = "normal"},
	["Sableye"] = {size = 90, animated = false, top = -8, left = -7, base = "ghost"},
	["Mawile"] = {size = 90, animated = false, top = -6, left = 0, base = "normal"},
	["Aron"] = {size = 90, animated = false, top = -8, left = -8, base = "rock"},
	["Lairon"] = {size = 90, animated = false, top = -8, left = -5, base = "rock"},
	["Aggron"] = {size = 90, animated = false, top = -8, left = 3, base = "rock"},
	["Meditite"] = {size = 90, animated = false, top = -8, left = -9, base = "fighting"},
	["Medicham"] = {size = 90, animated = false, top = -8, left = -9, base = "fighting"},
	["Electrike"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Manectric"] = {size = 90, animated = false, top = -8, left = -9, base = "normal"},
	["Plusle"] = {size = 90, animated = false, top = -8, left = -14, base = "normal"},
	["Minun"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	["Volbeat"] = {size = 90, animated = true, top = -8, left = -7, base = "grass"},
	["Illumise"] = {size = 90, animated = true, top = -8, left = -7, base = "grass"},
	["Roselia"] = {size = 90, animated = false, top = -8, left = -9, base = "grass"},
	["Gulpin"] = {size = 90, animated = false, top = -8, left = -15, base = "dark_forest"},
	["Swalot"] = {size = 90, animated = false, top = -8, left = -7, base = "dark_forest"},
	["Carvanha"] = {size = 90, animated = true, top = -8, left = -4, base = "water"},
	["Sharpedo"] = {size = 90, animated = true, top = -6, left = 12, base = "water"},
	["Wailmer"] = {size = 90, animated = false, top = -8, left = -4, base = "water"},
	["Wailord"] = {size = 60, animated = false, top = 30, left = 34, base = "water"},
	["Numel"] = {size = 90, animated = false, top = -8, left = -9, base = "ground"},
	["Camerupt"] = {size = 90, animated = false, top = -8, left = 7, base = "ground"},
	["Torkoal"] = {size = 90, animated = false, top = -8, left = -9, base = "fire"},
	["Spoink"] = {size = 90, animated = false, top = -8, left = -12, base = "psychic"},
	["Grumpig"] = {size = 90, animated = false, top = -8, left = -9, base = "psychic"},
	["Spinda"] = {size = 90, animated = false, top = -8, left = -5, base = "normal"},
	["Trapinch"] = {size = 90, animated = false, top = -8, left = -11, base = "desert"},
	["Vibrava"] = {size = 90, animated = true, top = -8, left = 4, base = "desert"},
	["Flygon"] = {size = 90, animated = true, top = -8, left = 4, base = "desert"},
	["Cacnea"] = {size = 90, animated = false, top = -4, left = -7, base = "grass"},
	["Cacturne"] = {size = 90, animated = false, top = -8, left = -4, base = "grass"},
	["Swablu"] = {size = 90, animated = true, top = -8, left = 2, base = "normal"},
	["Altaria"] = {size = 90, animated = false, top = -8, left = 24, base = "normal"},
	["Zangoose"] = {size = 90, animated = false, top = -8, left = -5, base = "normal"},
	["Seviper"] = {size = 90, animated = false, top = -8, left = -14, base = "dark_forest"},
	["Lunatone"] = {size = 90, animated = false, top = -8, left = -12, base = "rock"},
	["Solrock"] = {size = 85, animated = true, top = 4, left = 10, base = "rock"},
	["Barboach"] = {size = 90, animated = true, top = -8, left = -14, base = "water"},
	["Whiscash"] = {size = 90, animated = false, top = -2, left = 9, base = "water"},
	["Corphish"] = {size = 90, animated = false, top = -8, left = -7, base = "water"},
	["Crawdaunt"] = {size = 90, animated = false, top = -8, left = 5, base = "water"},
	["Baltoy"] = {size = 90, animated = true, top = -8, left = -7, base = "ground"},
	["Claydol"] = {size = 90, animated = false, top = -8, left = 0, base = "ground"},
	["Lileep"] = {size = 90, animated = false, top = -8, left = -7, base = "ground"},
	["Cradily"] = {size = 90, animated = false, top = -8, left = 1, base = "ground"},
	["Anorith"] = {size = 90, animated = false, top = -8, left = -13, base = "ground"},
	["Armaldo"] = {size = 90, animated = false, top = -8, left = -6, base = "ground"},
	["Feebas"] = {size = 90, animated = true, top = -8, left = -5, base = "water"},
	["Milotic"] = {size = 90, animated = false, top = -2, left = 15, base = "water"},
	["Castform"] = {size = 90, animated = true, top = -8, left = -7, base = "normal"},
	["Kecleon"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Shuppet"] = {size = 90, animated = true, top = -4, left = -9, base = "ghost"},
	["Banette"] = {size = 90, animated = false, top = -8, left = -12, base = "ghost"},
	["Duskull"] = {size = 90, animated = false, top = -8, left = -2, base = "ghost"},
	["Dusclops"] = {size = 90, animated = false, top = -8, left = -4, base = "ghost"},
	["Tropius"] = {size = 90, animated = false, top = -4, left = 15, base = "grass"},
	["Chimecho"] = {size = 90, animated = false, top = -8, left = -12, base = "psychic"},
	["Absol"] = {size = 90, animated = false, top = -8, left = -11, base = "ghost"},
	["Wynaut"] = {size = 90, animated = false, top = -8, left = -7, base = "psychic"},
	["Snorunt"] = {size = 90, animated = false, top = -4, left = -11, base = "ice"},
	["Glalie"] = {size = 90, animated = true, top = -4, left = -6, base = "ice"},
	["Spheal"] = {size = 90, animated = false, top = -8, left = -12, base = "water"},
	["Sealeo"] = {size = 90, animated = false, top = -4, left = -4, base = "water"},
	["Walrein"] = {size = 90, animated = false, top = -4, left = 3, base = "water"},
	["Clamperl"] = {size = 90, animated = false, top = -2, left = -7, base = "water"},
	["Huntail"] = {size = 90, animated = true, top = -8, left = -16, base = "water"},
	["Gorebyss"] = {size = 90, animated = true, top = -4, left = -7, base = "water"},
	["Relicanth"] = {size = 90, animated = true, top = -8, left = -14, base = "water"},
	["Luvdisc"] = {size = 90, animated = true, top = -8, left = -7, base = "water"},
	["Bagon"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Shelgon"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Salamence"] = {size = 80, animated = false, top = 4, left = 20, base = "normal"},
	["Beldum"] = {size = 90, animated = true, top = -8, left = -7, base = "normal"},
	["Metang"] = {size = 90, animated = true, top = -8, left = 10, base = "normal"},
	["Metagross"] = {size = 85, animated = false, top = 0, left = 20, base = "normal"},
	["Regirock"] = {size = 90, animated = false, top = -8, left = 12, base = "rock"},
	["Regice"] = {size = 90, animated = true, top = -8, left = 8, base = "ice"},
	["Registeel"] = {size = 90, animated = false, top = -8, left = 10, base = "normal"},
	["Latias"] = {size = 90, animated = true, top = -8, left = 10, base = "normal"},
	["Latios"] = {size = 90, animated = true, top = -8, left = 10, base = "normal"},
	["Kyogre"] = {size = 80, animated = false, top = 0, left = 28, base = "water"},
	["Groudon"] = {size = 80, animated = false, top = 4, left = 20, base = "ground"},
	["Rayquaza"] = {size = 70, animated = false, top = 17, left = 35, base = "normal"},
	["Jirachi"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Deoxys"] = {size = 90, animated = false, top = -8, left = -7, base = "space"},
	
	
	["Underworld Pikachu"] = {size = 90, animated = false, top = -8, left = -2, base = "distortion"},
	["Big Onix"] = {size = 65, animated = false, top = 25, left = 19, base = "rock"},
	["Shiny Snorlax"] = {size = 75, animated = false, top = 10, left = 23, base = "normal"},
	["Crystal Onix"] = {size = 90, animated = false, top = 0, left = 0, base = "crystal"},
	
	
	-- ADDONS POKEMON
	["Shiny Charizard Skull Set"] = {size = 90, animated = false, top = -8, left = 7, base = "fire"},
	
	["Charizard Scar Makeup"] = {size = 90, animated = false, top = -8, left = 7, base = "fire"},
	["Charizard Armors"] = {size = 90, animated = false, top = -8, left = 7, base = "fire"},
	["Charizard Charla Flower"] = {size = 90, animated = false, top = -8, left = 7, base = "fire"},
	
	["Growlithe Stylish Fur"] = {size = 90, animated = false, top = -6, left = -11, base = "fire"},
	["Growlithe Dog Collar"] = {size = 90, animated = false, top = -6, left = -11, base = "fire"},
	
	["Pidgeotto Flying Glasses"] = {size = 90, animated = false, top = -8, left = 2, base = "normal"},
	
	["Farfetch'd Pimp Costume"] = {size = 90, animated = false, top = -8, left = -12, base = "normal"},
	
	["Sandslash Metal Claws"] = {size = 90, animated = false, top = -11, left = -7, base = "ground"},
	["Sandslash Old Man Glasses"] = {size = 90, animated = false, top = -11, left = -7, base = "ground"},
	["Sandslash Z-Shirt"] = {size = 90, animated = false, top = -11, left = -7, base = "ground"},
	
	["Gengar Pirate Bandana"] = {size = 90, animated = false, top = -8, left = -2, base = "ghost"},
	["Gengar Purplebeard Costume"] = {size = 90, animated = false, top = -8, left = -2, base = "ghost"},
	
	["Scyther Scar Makeup"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	["Scyther Assassin's Cape"] = {size = 90, animated = false, top = -8, left = 0, base = "normal"},
	
	["Blastoise Scar Makeup"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Blastoise Ninja Costume 1"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Blastoise Ninja Costume 2"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Blastoise Ninja Costume 3"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Blastoise Ninja Costume 4"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	["Blastoise Ninja Costume 5"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	
	["Shiny Blastoise Ninja Costume"] = {size = 90, animated = false, top = -8, left = 7, base = "water"},
	
	["Rhyhorn Crystal Makeup"] = {size = 90, animated = false, top = -8, left = -2, base = "rock"},
	
	["Graveler Crystal Makeup"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	["Graveler Doomed Costume"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	["Graveler Prisoner Costume"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	
	["Nidoking Royal Swords"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	["Nidoking Royal Weapons"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	
	["Nidoqueen Magician Weapons"] = {size = 90, animated = false, top = -7, left = 2, base = "normal"},
	
	["Shiny Nidoking King Crowns"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	["Shiny Nidoking Prisoner Helms"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	["Shiny Nidoking Christmas Hat"] = {size = 90, animated = false, top = -7, left = 8, base = "normal"},
	
	["Pidgey Magician Hat"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Pidgey Skeleton Mask"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	["Pidgey Zombie Mask"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	
	["Raticate Master Rat Costume"] = {size = 90, animated = false, top = -6, left = -7, base = "normal"},
	
	["Pidgeot Flying Glasses"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Pidgeot Purple Scarf"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Pidgeot Green Scarf"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	["Pidgeot Blue Scarf"] = {size = 90, animated = false, top = -8, left = -7, base = "normal"},
	
	["Rhydon Spiked Armlet"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	["Rhydon Berserker Flails"] = {size = 90, animated = false, top = -8, left = 2, base = "rock"},
	
	["Squirtle Squad Jacket"] = {size = 90, animated = false, top = -6, left = -7, base = "water"},
	["Squirtle Squad Leader Jacket"] = {size = 90, animated = false, top = -6, left = -7, base = "water"},
	
	["Shiny Flareon Metal Set"] = {size = 90, animated = false, top = -6, left = -4, base = "fire"},
	["Shiny Flareon Christmas Hat"] = {size = 90, animated = false, top = -6, left = -4, base = "fire"},
	
	["Shiny Hypno Crazy Clown Costume"] = {size = 90, animated = false, top = -8, left = -4, base = "psychic"},
	["Shiny Hypno Bad Clown Costume"] = {size = 90, animated = false, top = -8, left = -4, base = "psychic"},
	["Shiny Hypno Christmas Hat"] = {size = 90, animated = false, top = -8, left = -4, base = "psychic"},
	
	["Shiny Golem Spiked Set"] = {size = 90, animated = false, top = -8, left = 4, base = "rock"},
	["Shiny Golem Christmas Hat"] = {size = 90, animated = false, top = -8, left = 4, base = "rock"},
	
	["Shiny Jolteon Metal Set"] = {size = 90, animated = false, top = -6, left = -6, base = "normal"},
	["Shiny Jolteon Christmas Hat"] = {size = 90, animated = false, top = -6, left = -6, base = "normal"},
	
	["Elite Hitmontop Robin Costume"] = {size = 90, animated = false, top = -8, left = -8, base = "fighting"},
	["Elite Hitmontop Christmas Hat"] = {size = 90, animated = false, top = -8, left = -8, base = "fighting"},
	
	["Shiny Vileplume Mexican Costume"] = {size = 90, animated = false, top = -8, left = 1, base = "grass"},
	["Shiny Vileplume Bob Costume"] = {size = 90, animated = false, top = -8, left = 1, base = "grass"},
	["Shiny Vileplume Christmas Hat"] = {size = 90, animated = false, top = -8, left = 1, base = "grass"},
	
	["Elite Hitmonchan Batman Costume"] = {size = 90, animated = false, top = -8, left = -7, base = "fighting"},
	
	["Shiny Vaporeon Metal Set"] = {size = 90, animated = false, top = -6, left = -4, base = "water"},
	["Shiny Vaporeon Christmas Hat"] = {size = 90, animated = false, top = -6, left = -4, base = "water"},
	
	["Shiny Fearow Metal Set"] = {size = 90, animated = true, top = -6, left = 11, base = "normal"},
	["Shiny Fearow Christmas Hat"] = {size = 90, animated = true, top = -6, left = 11, base = "normal"},
	
	["Shiny Arcanine Christmas Hat"] = {size = 90, animated = false, top = -4, left = 12, base = "fire"},
	
	["Shiny Tentacruel Christmas Hat"] = {size = 90, animated = true, top = -8, left = 6, base = "water"},
	
	["Shiny Pinsir Christmas Hat"] = {size = 90, animated = false, top = -6, left = 1, base = "normal"},
	
	["Shiny Tauros Christmas Hat"] = {size = 90, animated = false, top = -5, left = -6, base = "normal"},
	
	["Shiny Mr. Mime Christmas Hat"] = {size = 90, animated = false, top = -8, left = -2, base = "psychic"},
	
	["Shiny Raichu Christmas Hat"] = {size = 90, animated = false, top = -11, left = -5, base = "normal"},
	
	["Shiny Dragonair Christmas Hat"] = {size = 90, animated = false, top = -2, left = -2, base = "normal"},
	-- ADDONS POKEMON
}

-- modules.game_pokemon.doGetPokemonThings()
function doGetPokemonThings()
  return pokemonThingsPositionLocal
end